/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    AppMain: typeof import('./src/components/AppMain.vue')['default']
    BookEdit: typeof import('./src/components/BookEdit.vue')['default']
    Books: typeof import('./src/components/Books.vue')['default']
    BookView: typeof import('./src/components/BookView.vue')['default']
    ChooseRole: typeof import('./src/components/ChooseRole.vue')['default']
    copy: typeof import('./src/components/Login copy.vue')['default']
    CustomInput: typeof import('./src/components/CustomInput.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./src/components/SignUp.vue')['default']
  }
}
